repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        args:
          - --max-line-length=80
          - -d duplicate-code
          - --const-naming-style=UPPER_CASE
          - --function-naming-style=snake_case
          - --argument-naming-style=snake_case
          - --variable-naming-style=snake_case
